# Generated by Django 2.0.2 on 2018-05-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalments',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Num. da parcela'),
        ),
    ]
