# Generated by Django 2.0.2 on 2018-05-01 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_instalments_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalmentsCreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da parcela')),
                ('number', models.IntegerField(default=0, verbose_name='Num. da parcela')),
                ('month', models.DateField(blank=True, null=True, verbose_name='mês referencia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseCreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('local', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local')),
                ('num_instaments', models.IntegerField(verbose_name='Num. parcelas')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da compra')),
                ('date', models.DateField(verbose_name='Data da compra')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.RemoveField(
            model_name='instalments',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='card',
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Conta', 'verbose_name_plural': 'Contas'},
        ),
        migrations.AlterModelOptions(
            name='creditcard',
            options={'verbose_name': 'Cartão', 'verbose_name_plural': 'Cartões'},
        ),
        migrations.AlterField(
            model_name='account',
            name='agency',
            field=models.CharField(blank=True, default='000', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(blank=True, default='000', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='operation',
            field=models.CharField(blank=True, default='000', max_length=8, null=True),
        ),
        migrations.DeleteModel(
            name='Instalments',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.AddField(
            model_name='purchasecreditcard',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartao', to='customers.CreditCard', verbose_name='Cartão'),
        ),
        migrations.AddField(
            model_name='instalmentscreditcard',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='customers.PurchaseCreditCard', verbose_name='Compra'),
        ),
    ]
