# Generated by Django 2.0.2 on 2018-05-01 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20180501_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='client',
        ),
        migrations.AlterModelOptions(
            name='instalmentscreditcard',
            options={'verbose_name': 'Parcela', 'verbose_name_plural': 'Parcelas'},
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='account',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='final',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
