# Generated by Django 2.0.2 on 2018-05-01 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20180501_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='customers.Client'),
        ),
    ]
