# Generated by Django 2.0.2 on 2018-05-02 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_creditcard_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasecreditcard',
            old_name='num_instaments',
            new_name='instalments_number',
        ),
    ]
